PICKLES_DIR = '/home/wade/PycharmProjects/chetflix/src/pickle_farm/data_backups/pickles'

ENABLE_REPLACEMENTS = False

LANG_REPLACEMENTS = {}

LANGUAGE_COLUMNS = [
    'dub_Arabic (Egypt) - Audio Description',
    'dub_Italian - Audio Description',
    'dub_Indonesian',
    'dub_Norwegian - Audio Description',
    'dub_Swiss German [Original]',
    'dub_French - Audio Descri',
    'dub_Russian',
    'dub_Italian - A',
    'dub_Estonian',
    'dub_European Spanish - Audio De',
    'dub_Polish - Audio Description',
    'dub_No Dialogue',
    'dub_Telugu [Original]',
    'dub_Mandarin (Guoyu) - Audio Description',
    'dub_Arabic (Jordan) [Original]',
    'dub_Turkish [Original]',
    'dub_Polish - Dubbing',
    'dub_Cantonese',
    'dub_Hungarian - Audio Description',
    'dub_Spanish -',
    'dub_Arabic (Palestine) [Original]',
    'dub_Danish - Audio Description',
    'dub_Hungarian [Original]',
    'dub_Slovenian [Original]',
    'dub_Brazilian',
    'dub_Yoruba',
    'dub_Tamil [Original]',
    'dub_Hindi [Original]',
    'dub_Danish [Original]',
    'dub_Multiple languages [Original]',
    'dub_Wolof [Original]',
    'dub_German',
    'dub_Vietnamese',
    'dub_Swahili [Original]',
    'dub_Arabic',
    'dub_English - Audio Description',
    'dub_Portugues',
    'dub_Swahili',
    'dub_French - Audio Description',
    'dub_Xhosa',
    'dub_Italian',
    'dub_Amharic [Original]',
    'dub_Dutch - Audio Description',
    'dub_Mandarin',
    'dub_Tagalog - Audio Description',
    'dub_Icelandic - Audio Description',
    'dub_Spanish - Audio Des',
    'dub_Turkish - Audio Description',
    'dub_Dutch',
    'dub_Quechua (Peru) [Original]',
    'dub_Arabic (Palestine)',
    'dub_Malayalam [Original]',
    'dub_Finnish [Original]',
    'dub_Spanish (Argentina) [Original]',
    'dub_British English - Audio Description',
    'dub_Arabic (Saudi Arabia) [Original]',
    'dub_Japanese',
    'dub_Punjabi [Original]',
    'dub_Australian English',
    'dub_Filipino [Original]',
    'dub_Russian - Audio Description',
    'dub_Tibetan [Original]',
    'dub_Polish',
    'dub_Cantonese [Original]',
    'dub_Spanish',
    'dub_Thai',
    'dub_German - Audio Desc',
    'dub_Arabic (Syria)',
    'dub_European Spanish - Dubbed',
    'dub_Bulgarian',
    'dub_European Spanish [English-Delayed]',
    'dub_Hebrew - Audio Description',
    'dub_Japanese [English-Delayed]',
    'dub_European Spanish - Audio Desc',
    'dub_Arabic (Lebanon) [Original]',
    'dub_Tagalog [Original]',
    'dub_Arabic (United Arab Emirates) [Original]',
    'dub_Hebrew',
    'dub_Spanish [Original]',
    'dub_Southern Sotho [Original]',
    'dub_Arabic (Egypt) [Original]',
    'dub_Norwegian [Original]',
    'dub_Romanian',
    'dub_Arabic - Audio Descriptio',
    'dub_Icelandic',
    'dub_Japanese [Original]',
    'dub_Vietnamese [Original]',
    'dub_Aramaic [Original]',
    'dub_Yiddish [Original]',
    'dub_Korean',
    'dub_European Spanish',
    'dub_Slovenian',
    'dub_Finnish - Audio Description',
    'dub_French',
    'dub_Swedish',
    'dub_Ukrainian',
    'dub_Javanese [Original]',
    'dub_Malay - Audio Description',
    'dub_Catalan [Original]',
    'dub_Malay',
    'dub_Basque - Audio Description',
    'dub_Finnish',
    'dub_Thai - Audio Description',
    'dub_Brazilian Portuguese - Audio Description',
    'dub_Undefined',
    'dub_Hindi - Audio Description',
    'dub_Telugu',
    'dub_European Spanish - Audio',
    'dub_Czech [Original]',
    'dub_Marathi [Original]',
    'dub_Hindi [English-Delayed]',
    'dub_Icelandic [Original]',
    'dub_Thai [Original]',
    'dub_Catalan',
    'dub_Slovak [Original]',
    'dub_Brazilian Portuguese',
    'dub_Javanese - Audio Description',
    'dub_Latin [Original]',
    'dub_Serbian [Original]',
    'dub_Urdu',
    'dub_Zulu',
    'dub_Flemish [Original]',
    'dub_European Spanish - Dubbed - Audio Description',
    'dub_Arabic (Morocco) [Original]',
    'dub_Hindi',
    'dub_Cantonese - Audio Description',
    'dub_Spanish - Audio Description',
    'dub_European Spanish [English-Pending]',
    'dub_Afrikaans',
    'dub_Aymara [Original]',
    'dub_Simplified Chinese',
    'dub_English (India) [Original]',
    'dub_Hausa [Original]',
    'dub_Russian [Original]',
    'dub_Polish -',
    'dub_Flemish - Audio Description',
    'dub_Mandarin (Putonghua)',
    'dub_Tamil - Audio Description',
    'dub_Korean - Audio Description',
    'dub_German - Dubbed - Audio Description',
    'dub_Flemish',
    'dub_Yoruba [Original]',
    'dub_English [Hindi-Delayed]',
    'dub_Arabic [Original]',
    'dub_Basque [Original]',
    'dub_Kannada',
    'dub_Tamil',
    'dub_Thai - Dubbed',
    'dub_Marathi',
    'dub_Swedish [Original]',
    'dub_Spanish - A',
    'dub_Bangla [Original]',
    'dub_Brazilian Portuguese [English-Pending]',
    'dub_Mandarin (Guoyu) [Original]',
    'dub_No Dialogue [Original]',
    'dub_Mongolian [Original]',
    'dub_Bangla',
    'dub_Wolof - Audio Description',
    'dub_Canadian French',
    'dub_Polish - Lektor',
    'dub_Gujarati',
    'dub_Australian English [Original]',
    'dub_Mexican Spanish',
    'dub_Lingala [Original]',
    'dub_Arabic (Egypt)',
    'dub_Malay [Original]',
    'dub_Indonesian - Audio Description',
    'dub_Brazilian Portuguese [Original]',
    'dub_Mandarin [Original]',
    'dub_Czech',
    'dub_Urdu [Original]',
    'dub_Mandarin (Putonghua) - Audio Description',
    'dub_Georgian [Original]',
    'dub_Turkish',
    'dub_Greek',
    'dub_Canadian French - Audio Description',
    'dub_Persian [Original]',
    'dub_Galician [Original]',
    'dub_Afrikaans [Original]',
    'dub_Filipino - Audio Description',
    'dub_Hindi [English-Pending]',
    'dub_Gujarati [Original]',
    'dub_English (India) - Audio Description',
    'dub_Norwegian',
    'dub_European Spanish - Audio Description',
    'dub_Nepali [Original]',
    'dub_Marathi - Audio Description',
    'dub_Polish [Original]',
    'dub_Mandarin - Audio Description',
    'dub_Mandarin (Putonghua) [Original]',
    'dub_Romanian - Audio Description',
    'dub_Assamese [Original]',
    'dub_Ukrainian [Original]',
    'dub_Min Nan Chinese [Original]',
    'dub_Southern Sotho',
    'dub_Sanskrit [Original]',
    'dub_European Spanish [Original]',
    'dub_Lithuanian',
    'dub_Ukrainian - Audio Description',
    'dub_Dari [Original]',
    'dub_Kannada [Original]',
    'dub_Portuguese',
    'dub_Croatian',
    'dub_English',
    'dub_British English [Original]',
    'dub_Korean [Original]',
    'dub_Hebrew [Original]',
    'dub_Arabic (Syria) [Original]',
    'dub_Brazilian Portuguese - A',
    'dub_Dutch [Original]',
    'dub_Khmer [Original]',
    'dub_Bulgarian [Original]',
    'dub_Hausa',
    'dub_Zulu [Original]',
    'dub_Indonesian [Original]',
    'dub_German - Audio Description',
    'dub_Canadian French [Original]',
    'dub_Portuguese [Original]',
    'dub_French [Original]',
    'dub_Malayalam',
    'dub_Swedish - Audio Description',
    'dub_Belarusian [Original]',
    'dub_Japanese - Audio Description',
    'dub_Portuguese - Audio Description',
    'dub_Vietnamese - Audio Description',
    'dub_Hungarian',
    'dub_Italian [Original]',
    'dub_German [Original]',
    'dub_Mandarin (Guoyu)',
    'dub_Brazilian Portugues',
    'dub_English [Original]',
    'dub_British English',
    'dub_Slovak',
    'dub_Danish',
    'dub_Brazilian Portuguese [English-Delayed]',
    'dub_Arabic - Audio Description',
    'dub_Romanian [Original]',
    'sub_Georgian',
    'sub_Hindi',
    'sub_Brazilian Portuguese',
    'sub_English (India)',
    'sub_Mandarin (Guoyu)',
    'sub_Bulgarian',
    'sub_Danish',
    'sub_German [Original]',
    'sub_Tagalog',
    'sub_Traditional Chinese (Hong Kong SAR China)',
    'sub_Polish [Original]',
    'sub_Greek',
    'sub_Arabic (Lebanon)',
    'sub_Arabic (Lebanon) [Original]',
    'sub_English [Original]',
    'sub_Korean',
    'sub_Welsh',
    'sub_Cantonese',
    'sub_Finnish',
    'sub_British English',
    'sub_Hebrew',
    'sub_Undefined',
    'sub_Korean [Original]',
    'sub_Czech',
    'sub_Polish',
    'sub_Japanese [Original]',
    'sub_Slovak',
    'sub_Telugu',
    'sub_Papiamento',
    'sub_Swahili',
    'sub_Marathi',
    'sub_Bangla',
    'sub_Thai',
    'sub_Icelandic',
    'sub_English',
    'sub_Spanish',
    'sub_Swedish [Original]',
    'sub_Romanian',
    'sub_Filipino',
    'sub_Javanese',
    'sub_Malay [Original]',
    'sub_Norwegian',
    'sub_Macedonian',
    'sub_Tamil',
    'sub_English - Audio Description',
    'sub_Russian',
    'sub_Ukrainian',
    'sub_Flemish',
    'sub_European Spanish',
    'sub_Indonesian',
    'sub_German',
    'sub_Simplified Chinese',
    'sub_Arabic',
    'sub_Mandarin [Original]',
    'sub_Serbian (Latin)',
    'sub_Italian',
    'sub_Slovenian',
    'sub_Portuguese',
    'sub_Lithuanian',
    'sub_Turkish',
    'sub_Basque',
    'sub_Arabic (Egypt)',
    'sub_French',
    'sub_Arabic (Saudi Arabia)',
    'sub_Croatian',
    'sub_Wolof',
    'sub_Japanese',
    'sub_Canadian French',
    'sub_Hungarian',
    'sub_Mandarin',
    'sub_Swedish',
    'sub_Vietnamese',
    'sub_Malay',
    'sub_Catalan',
    'sub_Traditional Chinese',
    'sub_Dutch'
]
