from pathlib import Path

from src.unogs import INPUT_FOLDER, OUTPUT_FOLDER, PICKLE_FOLDER
from src.utils import read_json


def setup_directories():
    INPUT_FOLDER.mkdir(exist_ok=True)
    OUTPUT_FOLDER.mkdir(exist_ok=True)
    PICKLE_FOLDER.mkdir(exist_ok=True)


def load_netflix_nametags():
    """
    Load file from JSON dat generated by the Nametags function.

    :param filename: str
    :return: dict
    """
    nf_path = Path(INPUT_FOLDER, 'netflix_nametags.json')

    """
    If nf_dict doesn't exist, raise an error
    """
    if not nf_path.exists():
        raise FileNotFoundError('Missing Netflix Nametags file')

    """
    Load from nf_dict
    """
    return read_json(nf_path)