import os
from pathlib import Path

from src.utils import read_json


def setup_directories() -> Path:
    """
    Directory Setup:

    Defines the directories for input and output data.


    """
    home_dir = Path(os.getcwd())

    input_folder = Path(home_dir, 'inputs')
    output_folder = Path(home_dir, 'results')
    pickle_folder = Path(home_dir, 'pickles')

    input_folder.mkdir(exist_ok=True)
    output_folder.mkdir(exist_ok=True)
    pickle_folder.mkdir(exist_ok=True)

    return pickle_folder


def load_netflix_nametags() -> list:
    """
    Load file from JSON data generated by the Nametags function.

    :return: dict
    """
    nf_path = Path(os.getcwd(), 'inputs', 'netflix_nametags.json')

    """
    If nf_dict doesn't exist, raise an error
    """
    if not nf_path.exists():
        raise FileNotFoundError('Missing Netflix Nametags file')

    """
    Load from nf_dict
    """
    return read_json(nf_path)


def load_replacements() -> dict:
    try:
        data = read_json(Path(os.getcwd(), 'inputs', 'original_language_replacements.json'))
    except FileNotFoundError:
        return {}
    else:
        return data
